import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "./lib/queryProvider";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          {children}
        </QueryProvider>
        
      </body>
    </html>
  );
}
