import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "./lib/queryProvider";
import ReduxProvider from "./state/reduxProvider";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <QueryProvider>
            {children}
          </QueryProvider>
        </ReduxProvider>
        
      </body>
    </html>
  );
}
